  <nav id="menu" class="navbar navbar-expand-lg navbar fixed-top navbar-light">
      <a id="brand" class="navbar-brand" href="index.php">Ida K.T</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          
          <li class="nav-item dropdown">
            <a id="web" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Webudvikling
            </a>
            <div id="webtext" class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="historie.php">Historie</a>
                
              <a class="dropdown-item" href="server.php">Server</a>
                
              <a class="dropdown-item" href="html.php">HTML</a>
                
              <a class="dropdown-item" href="css.php">CSS</a>
                
              <a class="dropdown-item" href="versionsstyring.php">Versionsstyring</a>
                
              <a class="dropdown-item" href="informationsarkitektur.php">Informationsarkitektur</a>
                
              <a class="dropdown-item" href="planlægningoverordnetdesign.php">Planlægning/Overordnet design</a>     
            </div>
          </li>
            
         <li class="nav-item dropdown">
            <a id="kom" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Kommunikation
            </a>
            <div id="ktekst" class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="kommunikation.php">Kommunikation</a>
              <a class="dropdown-item" href="produktionsmodeller.php">Produktionsmodeller</a>
              
              <a class="dropdown-item" href="præsentationsteknik.php">Præsentationsteknik</a>
                
              
                <a class="dropdown-item" href="#">Digitalemedier/Platforme</a>
              
                <a class="dropdown-item" href="#">Tekstproduktion</a>
              
                <a class="dropdown-item" href="#">Brugertest</a>
              
                <a class="dropdown-item" href="#">Business Model Canvas</a>    
            </div>
        </li>
            
        <li class="nav-item dropdown">
            <a id="design"class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Design
            </a>
            <div id="dtekst" class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Photoshop</a>
                 
              <a class="dropdown-item" href="#">Illustrator</a>
              
              <a class="dropdown-item" href="#">Fotografering</a>
               
                <a class="dropdown-item" href="#">Farver</a>
            
                <a class="dropdown-item" href="#">Gestaltlove</a>   
            </div>
          </li>
            
            
            <li class="nav-item dropdown">
             <a id="pro" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Projekter
             </a>
            <div id="ptekst" class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="#">Onepage</a>
                 
              <a class="dropdown-item" href="#">Designthinking</a>
              
              <a class="dropdown-item" href="#">Første hjemmeside</a>
                
                <a class="dropdown-item" href="#">Workshop - Css/Html</a>  
            </div>
          </li>
            
        </ul>
      </div>
    </nav> 
      
    <div id="luftundermenu"> &nbsp;
    </div>